# Generated by Django 2.1.2 on 2018-11-15 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=500)),
                ('business_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.ManyToManyField(null=True, related_name='class1', to='login.Class')),
                ('class2', models.ManyToManyField(blank=True, null=True, related_name='class2', to='login.Class')),
                ('class3', models.ManyToManyField(blank=True, null=True, related_name='class3', to='login.Class')),
                ('class4', models.ManyToManyField(blank=True, null=True, related_name='class4', to='login.Class')),
            ],
        ),
        migrations.CreateModel(
            name='user_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.ManyToManyField(null=True, related_name='uskill1', to='login.Skill')),
                ('skill2', models.ManyToManyField(blank=True, null=True, related_name='uskill2', to='login.Skill')),
                ('skill3', models.ManyToManyField(blank=True, null=True, related_name='uskill3', to='login.Skill')),
                ('skill4', models.ManyToManyField(blank=True, null=True, related_name='uskill4', to='login.Skill')),
                ('skill5', models.ManyToManyField(blank=True, null=True, related_name='uskill5', to='login.Skill')),
                ('skill6', models.ManyToManyField(blank=True, null=True, related_name='uskill6', to='login.Skill')),
                ('skill7', models.ManyToManyField(blank=True, null=True, related_name='uskill7', to='login.Skill')),
                ('skill8', models.ManyToManyField(blank=True, null=True, related_name='uskill8', to='login.Skill')),
                ('skill9', models.ManyToManyField(blank=True, null=True, related_name='uskill9', to='login.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('courses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user_classes')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Major')),
                ('skills', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user_skills')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Major'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_skill1',
            field=models.ManyToManyField(null=True, related_name='jskil1', to='login.Skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_skill2',
            field=models.ManyToManyField(blank=True, null=True, related_name='jskil2', to='login.Skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_skill3',
            field=models.ManyToManyField(blank=True, null=True, related_name='jskil3', to='login.Skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_skill4',
            field=models.ManyToManyField(blank=True, null=True, related_name='jskil4', to='login.Skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_skill5',
            field=models.ManyToManyField(blank=True, null=True, related_name='jskil5', to='login.Skill'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_skill1',
            field=models.ManyToManyField(null=True, related_name='cskill1', to='login.Skill'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_skill2',
            field=models.ManyToManyField(blank=True, null=True, related_name='cskill2', to='login.Skill'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_skill3',
            field=models.ManyToManyField(blank=True, null=True, related_name='cskill3', to='login.Skill'),
        ),
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Major'),
        ),
    ]
